package com.securetransact.model;

public enum AuditAction {
    USER_REGISTERED,
    USER_LOGIN,
    USER_LOGOUT,
    PASSWORD_CHANGED,
    ACCOUNT_CREATED,
    ACCOUNT_FROZEN,
    ACCOUNT_UNFROZEN,
    TRANSACTION_CREATED,
    TRANSACTION_SETTLED,
    TRANSACTION_REVERSED,
    TRANSACTION_HELD,
    TRANSACTION_REJECTED,
    TRANSACTION_FAILED,
    RISK_CASE_CREATED,
    RISK_CASE_ASSIGNED,
    RISK_CASE_APPROVED,
    RISK_CASE_REJECTED,
    RISK_CASE_ESCALATED,
    RULE_CONFIG_UPDATED,
    BLACKLIST_UPDATED
}
